apiVersion: v1
kind: LimitRange
metadata:
        name: testing
spec:
        limits:
                - type: Container
                  max:
                          cpu: 2
                          memory: 1Gi
                  min:
                          cpu: 500m
                          memory: 500Mi
                  default:
                          cpu: 1
                          memory: 700Mi
                  defaultRequest:
                          cpu: 750m
                          memory: 512Mi
                - type: Pod
                  max:
                          cpu: 2
                          memory: 1Gi
                  min:
                          cpu: 500m
                          memory: 500Mi
